"""initial schema

Revision ID: cf1214a1efd2
Revises:
Create Date: 2026-09-22 21:41:42.117183

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf1214a1efd2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
    )
    op.create_index(op.f("ix_students_email"), "students", ["email"], unique=True)
    op.create_table(
        "documents",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "DONE", "FAILED", name="document_status"),
            nullable=False,
        ),
        sa.Column("exam_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.id"], name=op.f("fk_documents_student_id_students"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(op.f("ix_documents_content_hash"), "documents", ["content_hash"], unique=False)
    op.create_index(op.f("ix_documents_student_id"), "documents", ["student_id"], unique=False)
    op.create_table(
        "topics",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_topics_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
    )
    op.create_index(op.f("ix_topics_document_id"), "topics", ["document_id"], unique=False)
    op.create_table(
        "mastery_scores",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("score >= 0 AND score <= 1", name=op.f("ck_mastery_scores_score_range")),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_mastery_scores_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_mastery_scores_topic_id_topics"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mastery_scores")),
        sa.UniqueConstraint("student_id", "topic_id", name="uq_mastery_scores_student_topic"),
    )
    op.create_index(op.f("ix_mastery_scores_student_id"), "mastery_scores", ["student_id"], unique=False)
    op.create_index(op.f("ix_mastery_scores_topic_id"), "mastery_scores", ["topic_id"], unique=False)
    op.create_table(
        "study_kits",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column(
            "kit_type",
            sa.Enum("SUMMARY", "FLASHCARDS", "QUIZ", "PROBLEM_GUIDE", name="study_kit_type"),
            nullable=False,
        ),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("source_chunk_ids", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_study_kits_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_study_kits_topic_id_topics"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_kits")),
    )
    op.create_index(op.f("ix_study_kits_student_id"), "study_kits", ["student_id"], unique=False)
    op.create_index(op.f("ix_study_kits_topic_id"), "study_kits", ["topic_id"], unique=False)
    op.create_table(
        "subtopics",
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_subtopics_topic_id_topics"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subtopics")),
    )
    op.create_index(op.f("ix_subtopics_topic_id"), "subtopics", ["topic_id"], unique=False)
    op.create_table(
        "topic_prerequisites",
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("prerequisite_topic_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "topic_id != prerequisite_topic_id", name=op.f("ck_topic_prerequisites_no_self_loop")
        ),
        sa.ForeignKeyConstraint(
            ["prerequisite_topic_id"],
            ["topics.id"],
            name=op.f("fk_topic_prerequisites_prerequisite_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_topic_prerequisites_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_prerequisites")),
        sa.UniqueConstraint("topic_id", "prerequisite_topic_id", name="uq_topic_prerequisites_edge"),
    )
    op.create_index(
        op.f("ix_topic_prerequisites_prerequisite_topic_id"),
        "topic_prerequisites",
        ["prerequisite_topic_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_topic_prerequisites_topic_id"), "topic_prerequisites", ["topic_id"], unique=False
    )
    op.create_table(
        "quiz_attempts",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("study_kit_id", sa.UUID(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("score >= 0 AND score <= 1", name=op.f("ck_quiz_attempts_score_range")),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_quiz_attempts_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["study_kit_id"],
            ["study_kits.id"],
            name=op.f("fk_quiz_attempts_study_kit_id_study_kits"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_quiz_attempts_topic_id_topics"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_attempts")),
    )
    op.create_index(op.f("ix_quiz_attempts_student_id"), "quiz_attempts", ["student_id"], unique=False)
    op.create_index(op.f("ix_quiz_attempts_topic_id"), "quiz_attempts", ["topic_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_attempts_topic_id"), table_name="quiz_attempts")
    op.drop_index(op.f("ix_quiz_attempts_student_id"), table_name="quiz_attempts")
    op.drop_table("quiz_attempts")
    op.drop_index(op.f("ix_topic_prerequisites_topic_id"), table_name="topic_prerequisites")
    op.drop_index(op.f("ix_topic_prerequisites_prerequisite_topic_id"), table_name="topic_prerequisites")
    op.drop_table("topic_prerequisites")
    op.drop_index(op.f("ix_subtopics_topic_id"), table_name="subtopics")
    op.drop_table("subtopics")
    op.drop_index(op.f("ix_study_kits_topic_id"), table_name="study_kits")
    op.drop_index(op.f("ix_study_kits_student_id"), table_name="study_kits")
    op.drop_table("study_kits")
    sa.Enum(name="study_kit_type").drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f("ix_mastery_scores_topic_id"), table_name="mastery_scores")
    op.drop_index(op.f("ix_mastery_scores_student_id"), table_name="mastery_scores")
    op.drop_table("mastery_scores")
    op.drop_index(op.f("ix_topics_document_id"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_documents_student_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_content_hash"), table_name="documents")
    op.drop_table("documents")
    sa.Enum(name="document_status").drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f("ix_students_email"), table_name="students")
    op.drop_table("students")
    # ### end Alembic commands ###
